### ISSUE TITLE
Optimize damage tracking

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#58]
- [ ] Track when a surface is on top of the other and don't get damage from the surface below

- [ ] Redraw only damaged parts of the offscreen buffer & later transforms

- [ ] Add a way for transformers to specify opaque regions after transform (for example, `wf_2D_view` without rotation should be able to set opaque region)
